common:
  name: kafka-research
  author: Linhnm20

kafka:
  bootstrap.servers: 94.10.10.131:9092
  topic: fenio
  group.id: fake-message-1

customer:
  total: 1000000
  max_waiting_time: 1000
  stayed_prop: 0.5
